version: '3'

networks:
  public:
    name: vpn_config
  private:
    name: lan_docker

volumes:
  db-data:
  www:

configs:
  php_config:
    file: ./php.ini
  bdd_config:
    file: ./mariadb.conf
  vpn_config:
    file: ./vpn.conf

services:
  bdd:
    container_name: mybdd
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: C1mdp2SQL!
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    ports:
      - 3306

  php:
    container_name: myphp
    image: bitnami/php-fpm:latest
    volumes:
      - www:/var/www/html
    networks:
      - private
    ports:
      - 8000:8000

  vpn:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
    - NET_ADMIN
    networks:
      - private
      - public
    environment:
    - PUID=$PUID
    - PGID=$PGID
    - TZ=$TZ
    - PEERS=Profile1,Profile2,OtherProfile
    volumes:
    - ./config:/config
    ports:
    ## port du serveur Wireguard
    - 51820:51820/udp
    ## port de l'interface de wireguard
    - 5000:5000
    restart: unless-stopped
  
  vpn-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: Wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - "NET_ADMIN"
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=password
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./config:/etc/wireguard
