version: '3.3'

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    ports:
      - '51821:51821/tcp'
      - '51820:51820/udp'
    volumes:
      - '.wg-easy:/etc/wireguard'
    environment:
      - WG_DEFAULT_ADDRESS=13.0.0.1x
      - WG_ALLOWED_IPS=10.0.0.0/8
      - WG_DEFAULT_DNS=8.8.8.8, 8.8.4.4
      - PASSWORD=C1mdp2Wireguard! # changer_moi
      - WG_HOST=192.168.1.100 # changez_moi
      - LANG=fr
      - WG_POST_UP=iptables -A FORWARD -i %i -j ACCEPT && iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_DOWN=iptables -D FORWARD -i %i -j ACCEPT && iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    container_name: wg-easy
    networks:
      wgnet:
        ipv4_address: 10.0.0.2

  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    depends_on:
      - wg-easy
    expose:
      - 5432
    networks:
      wgnet:
        ipv4_address: 10.0.0.3

  apache-php:
    image: php:8.3-apache
    restart: unless-stopped
    container_name: apache-php
    depends_on:
      - postgres
      - wg-easy
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
    volumes:
      - ./www:/var/www/html
    expose:
      - 80
    networks:
      wgnet:
        ipv4_address: 10.0.0.4
networks:
  wgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8
