version: '3'

networks:
  public:
    name: réseau publique exposé
  private:
    name: réseau privé pour les services php et BDD

volumes:
  db-data:
  www:

configs:
  php_config:
    file: ./php.ini
  bdd_config:
    file: ./mariadb.conf
  vpn_config:
    file: ./vpn.conf

services:
  bdd:
    container_name: mybdd
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: C1mdp2SQL!
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    ports:
      - 3306

  php:
    container_name: myphp
    image: bitnami/php-fpm:latest
    volumes:
      - www:/var/www/html
    networks:
      - private
    ports:
      - 8000:8000

  vpn:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
    - NET_ADMIN
    environment:
    - PUID=$PUID
    - PGID=$PGID
    - TZ=$TZ
    - PEERS=Profile1,Profile2,OtherProfile
    volumes:
    - $DOCKERDIR/appdata/wireguard:/config
    ports:
    - 51820:51820/udp
    sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    
    #image: olinuxserver/wireguard:latest
    #networks:
    #  - public
    #  - private
