version: '3.3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=192.168.1.100
      - SERVERPORT=51820
      - PEERS=client1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./wireguard/config:/config
      - ./wireguard/lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      wgnet:
        ipv4_address: 10.0.0.2

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    depends_on:
      - wireguard
    ports:
      - 5432:5432
    networks:
      wgnet:
        ipv4_address: 10.0.0.3

  apache-php:
    image: php:8.2-apache
    container_name: apache-php
    depends_on:
      - postgres
      - wireguard
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80
    networks:
      wgnet:
        ipv4_address: 10.0.0.4    

networks:
  wgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24