version: '3.3'

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=yourserverurl### ip publique du serveur 
      - SERVERPORT=51820
      - PEERS=client1,client2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.0.0.0/8
    volumes:
      - ./wireguard/config:/config
      - ./wireguard/lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    networks:
      - internal

  wireguard-ui:
    image:  ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    environment:
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=C1mdpAdm2WireGuard!
      - WGUI_ADDRESS=0.0.0.0
      - WGUI_PORT=5000
    volumes:
      - ./wireguard-ui/data:/data
    restart: unless-stopped
    depends_on:
      - wireguard
    networks:
      - internal

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    depends_on:
      - wireguard
    networks:
      - internal

  apache-php:
    image: php:8.2-apache
    container_name: apache-php
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
    volumes:
      - ./www:/var/www/html
    depends_on:
      - wireguard
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  internal:
    internal: true
